name    'dnna-pixelbonus'
version '0.1.0'
source 'UNKNOWN'
author 'dnna'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/mysql', '*'
dependency 'puppetlabs/vcsrepo', '*'
dependency 'willdurand-composer', '*'